spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        search:
          default:
            indexBase: ./index
            directory_provider: filesystem
  datasource:
    url: jdbc:postgresql://docker.local:5432/washeuteessen
    password: password
    username: postgres
  flyway:
    baseline-on-migrate: true
