spring:
  jpa:
    properties:
      hibernate:
        search:
          default:
            indexBase: ./index
            directory_provider: filesystem
  datasource:
    url: jdbc:h2:file:./index;DB_CLOSE_ON_EXIT=FALSE
