spring:
  jpa:
    properties:
      hibernate:
        search:
          default:
            indexBase: /index
            directory_provider: filesystem
  datasource:
    url: jdbc:h2:file:/index/database;DB_CLOSE_ON_EXIT=FALSE
server:
  tomcat:
    max-threads: 100
