spring:
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        search:
          default:
            indexBase: /index
            directory_provider: filesystem
server:
  tomcat:
    max-threads: 100

management.endpoint:
  metrics.enabled: true
  prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus
