CREATE TABLE RECIPE
(
  ID          SERIAL PRIMARY KEY NOT NULL,
  TITLE       TEXT               NOT NULL,
  DESCRIPTION TEXT,
  URL         TEXT
);

CREATE TABLE INGREDIENTS
(
  RECIPE_ID  INT  NOT NULL REFERENCES RECIPE,
  INGREDIENT TEXT NOT NULL
);

